---
title: Climate Reparations
email: ''
tagline: 'Climate Justice Now!'
description: There can be no climate justice without gender, racial, social, economic, health, migrant or environmental justice.
url: https://climatereparations.uk
permalink: pretty

theme: jekyll-theme-chaos

background_color: "#f4c6dc"
brand_color: "#9e61ae"
accent_color: "#f69008"
heading_font: 'Permanent Marker'
logo: '/assets/images/logo_text_yellow.png'
logo_light: '/assets/images/logo_text_white.png'
logo_square: '/assets/images/icon_small_yellow.png'
invert_brand_text: true
invert_accent_text: false
instagram: ''
twitter: ''
facebook: ''
counter: 06-Nov-2021 11am
timezone: Europe/London
future: true
copyright_notice: ''
collections:
  posts:
    permalink: "/posts/:title/"
  actions:
    output: true
  resources:
    output: true
  templates:
    output: false
defaults:
- scope:
    path: google2b8ceaa38de54302.html
  values:
    sitemap: false
- scope:
    path: admin/index.html
  values:
    sitemap: false
include:
  - _redirects
airtable:
  faqs:
    app: appbeeVjgr5W02dS6
    table: tbldebpIkoJcQcJ7T
    view: viwOD88M982tud2am
  posts:
    app: appbeeVjgr5W02dS6
    table: tbl6L6exCwnCfk3kI
    view: viwIriKfsUAns3dC4
    collection:
      slug: slug
      content: content
      layout: post
  partners:
    app: appbeeVjgr5W02dS6
    table: tblfczlNzhMZaUFX5
    view: viweY75HGX6wZo6AR
    fields:
    - Title
    - URL
    - Image
    - Summary
  demands:
    app:   appbeeVjgr5W02dS6
    table: tblM8icDWIdPicHZS
    view: viwtvRVZyEyH8s3Ml

plugins:
- jekyll-airtable-import
- jekyll-menus
