title: Climate Reparations
email: ''
tagline: Climate Justice Now!
description: >-
  There can be no climate justice without gender, racial, social, economic,
  health, migrant or environmental justice.
url: 'https://climatereparations.uk'
permalink: pretty
theme: jekyll-theme-chaos
background_color: '#f4c6dc'
brand_color: '#9e61ae'
accent_color: '#f69008'
heading_font: Coiny
logo: /assets/images/logo_text_yellow.png
logo_light: /assets/images/logo_text_white.png
logo_square: /assets/images/icon_small_yellow.png
invert_brand_text: true
invert_accent_text: false
instagram: ''
twitter: ''
facebook: ''
counter: '06-Nov-2021 11:30am'
timezone: Europe/London
future: true
copyright_notice: ''
collections:
  posts:
    permalink: '/:title/'
  actions:
    output: true
  resources:
    output: true
  templates:
    output: false
  authors:
    output: true
  petitions:
    output: true
  events:
    output: true
  campaigns:
    output: true
  forms:
    output: true
  advocacy_campaigns:
    output: true
    permalink: '/:categories/:slug/'
defaults:
  - scope:
      path: google2b8ceaa38de54302.html
    values:
      sitemap: false
  - scope:
      path: admin/index.html
    values:
      sitemap: false
include:
  - _redirects
airtable:
  faqs:
    app: appbeeVjgr5W02dS6
    table: tbldebpIkoJcQcJ7T
    view: viwOD88M982tud2am
  posts:
    table: tbl6L6exCwnCfk3kI
    view: viwIriKfsUAns3dC4
    collection:
      slug: slug
      content: content
      layout: post
  partners:
    table: tblfczlNzhMZaUFX5
    view: viweY75HGX6wZo6AR
    fields:
      - Title
      - URL
      - Image
      - Summary
  demands:
    table: tblM8icDWIdPicHZS
    view: viwtvRVZyEyH8s3Ml
  authors:
    table: tblBWrw6arE4jwnep
    collection:
      content: about
      slug: name
      layout: author
action_network:
  actions: false
  import:
    - name: events
      layout: an-page
    - name: petitions
      layout: an-page
    - name: forms
      layout: an-page
    - name: campaigns
      layout: an-page
    - name: advocacy_campaigns
      layout: an-page
exclude:
  - api
plugins:
  - jekyll-action-network
_template: config
