---
title: Climate Reparations
email: ''
tagline: 'Climate Justice Now!'
description: There can be no climate justice without gender, racial, social, economic, health, migrant or environmental justice.
url: https://climatereparations.uk
permalink: pretty

theme: jekyll-theme-chaos

background_color: "#e5eeff"
brand_color: rgb(70, 116, 229)
accent_color: rgb(70, 116, 229)
logo: ''
logo_light: ''
logo_square: ''
invert_brand_text: true
invert_accent_text: true
instagram: ''
twitter: ''
facebook: ''
counter: 06-Nov-2021 11am
timezone: Europe/London
future: true
copyright_notice: With thanks to [David Gundry](https://www.davidgundry.co.uk/) for
  the base theme.
collections:
  posts:
    permalink: "/stories/:title/"
  faqs:
    output: true
    permalink: "/faqs/:title/"
  trainings:
    output: true
  actions:
    output: true
  resources:
    output: true
  templates:
    output: false
defaults:
- scope:
    path: google2b8ceaa38de54302.html
  values:
    sitemap: false
- scope:
    path: admin/index.html
  values:
    sitemap: false
airtable:
  faqs:
    app: appbeeVjgr5W02dS6
    table: tbldebpIkoJcQcJ7T
    view: viwOD88M982tud2am
  resources:
    app: appbeeVjgr5W02dS6
    table: tbl6L6exCwnCfk3kI
    view: viwIriKfsUAns3dC4
  partners:
    app: appbeeVjgr5W02dS6
    table: tblfczlNzhMZaUFX5
    view: viweY75HGX6wZo6AR
    fields:
    - Title
    - URL
    - Image
    - Summary
  demands:
    app:   appbeeVjgr5W02dS6
    table: tblM8icDWIdPicHZS
    view: viwtvRVZyEyH8s3Ml
jekyll_get_json:
- data: events
  json: https://raw.githubusercontent.com/tippingpointuk/an-event-campaign-map/master/events.json
plugins:
- jekyll-airtable-import
- jekyll-get-json
