---
label: Config
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: email
  label: email
- type: text
  name: tagline
  label: tagline
- type: text
  name: description
  label: description
- type: text
  name: url
  label: url
- type: text
  name: permalink
  label: permalink
  hidden: true
- type: text
  name: background_color
  label: background_color
- type: file
  name: logo
  label: logo
- type: file
  name: logo_light
  label: logo_light
- type: file
  name: logo_square
  label: logo_square
- type: boolean
  name: invert_brand_text
  label: invert_brand_text
- type: boolean
  name: invert_accent_text
  label: invert_accent_text
- type: text
  name: instagram
  label: instagram
- type: text
  name: twitter
  label: twitter
- type: text
  name: facebook
  label: facebook
- type: text
  name: counter
  label: Count down to...
- type: field_group_list
  name: nav_links
  label: Navigation Links
  fields:
  - type: text
    name: url
    label: url
  - type: text
    name: title
    label: title
  description: Extra links added to the main navigation bar (i.e. links that are not
    pages)<br><br>To add/remove any other links to the nav just toggle Main Nav Exclude
    off or on for the relevant pages
  hidden: true
- type: boolean
  name: future
  label: future
  hidden: true
- type: text
  name: copyright_notice
  label: copyright_notice
- type: field_group
  name: collections
  label: collections
  fields:
  - type: field_group
    name: posts
    label: posts
    fields:
    - type: text
      name: permalink
      label: permalink
  - type: field_group
    name: faqs
    label: faqs
    fields:
    - type: boolean
      name: output
      label: output
    - type: text
      name: permalink
      label: permalink
  - type: field_group
    name: trainings
    label: trainings
    fields:
    - type: boolean
      name: output
      label: output
  - type: field_group
    name: actions
    label: actions
    fields:
    - type: boolean
      name: output
      label: output
  hidden: true
- type: field_group_list
  name: defaults
  label: defaults
  fields:
  - type: field_group
    name: scope
    label: scope
    fields:
    - type: text
      name: path
      label: path
  - type: field_group
    name: values
    label: values
    fields:
    - type: boolean
      name: sitemap
      label: sitemap
  hidden: true
- type: field_group
  name: airtable
  label: airtable
  fields:
  - type: field_group
    name: faqs
    label: faqs
    fields:
    - type: text
      name: app
      label: app
    - type: text
      name: table
      label: table
    - type: text
      name: view
      label: view
  - type: field_group
    name: resources
    label: resources
    fields:
    - type: text
      name: app
      label: app
    - type: text
      name: table
      label: table
    - type: text
      name: view
      label: view
  - type: field_group
    name: partners
    label: partners
    fields:
    - type: text
      name: app
      label: app
    - type: text
      name: table
      label: table
    - type: text
      name: view
      label: view
    - type: list
      name: fields
      label: fields
  - type: field_group
    name: trainings
    label: trainings
    fields:
    - type: text
      name: app
      label: app
    - type: text
      name: table
      label: table
    - type: text
      name: view
      label: view
    - type: list
      name: fields
      label: fields
    - type: field_group
      name: collection
      label: collection
      fields:
      - type: text
        name: slug
        label: slug
      - type: text
        name: layout
        label: layout
      - type: text
        name: content
        label: content
- type: field_group_list
  name: jekyll_get_json
  label: jekyll_get_json
  fields:
  - type: text
    name: data
    label: data
  - type: text
    name: json
    label: json
  hidden: true
- type: field_group
  name: map
  label: map
  fields:
  - type: text
    name: lat
    label: lat
  - type: text
    name: lng
    label: lng
  hidden: true
- type: list
  name: plugins
  label: plugins
  hidden: true
pages:
- _config.yml
